# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  appimaged = {
    pname = "appimaged";
    version = "appimaged-817-x86_64.AppImage";
    src = fetchurl {
      url = "https://github.com/probonopd/go-appimage/releases/download/continuous/appimaged-817-x86_64.AppImage";
      sha256 = "sha256-1pWGh4VJQn9AU1DJOni7fvlmV7EUKfDprGKViIF4ohI=";
    };
  };
}
